# Generated by Django 5.2.1 on 2025-10-04 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_demand', models.CharField(help_text='Current demand value in MW', max_length=50)),
                ('yesterday_demand', models.CharField(help_text="Yesterday's demand value in MW", max_length=50)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of when the data was captured')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
