# Generated by Django 5.2.1 on 2025-10-06 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0001_initial'),                       
    ]

    operations = [
        migrations.AddField(
            model_name='demanddata',
            name='reported_timestamp',
            field=models.DateTimeField(blank=True, help_text='The timestamp shown on the Vidyut PRAVAH website', null=True),
        ),
        migrations.AddField(
            model_name='demanddata',
            name='time_block_info',
            field=models.CharField(blank=True, help_text='The full time block string extracted from the site', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demanddata',
            name='captured_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of when the script captured the data'),
        ),
    ]
