# Generated by Django 5.2.1 on 2025-10-06 04:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0002_demanddata_reported_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanddata',
            name='reported_timestamp',
        ),
        migrations.RemoveField(
            model_name='demanddata',
            name='time_block_info',
        ),
        migrations.AlterField(
            model_name='demanddata',
            name='captured_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of when the data was captured'),
        ),
    ]
