# Generated by Django 5.2.1 on 2025-10-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0003_remove_demanddata_reported_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanddata',
            name='date',
            field=models.DateField(blank=True, help_text='The date extracted from the website', null=True),
        ),
        migrations.AddField(
            model_name='demanddata',
            name='time_block',
            field=models.CharField(blank=True, help_text='The time block string extracted from the site', max_length=50, null=True),
        ),
    ]
