# Generated by Django 5.2.1 on 2025-10-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0004_demanddata_date_demanddata_time_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demanddata',
            options={'ordering': ['-date', '-time_block']},
        ),
        migrations.RemoveField(
            model_name='demanddata',
            name='captured_at',
        ),
    ]
