# Generated by Django 5.2.1 on 2025-10-06 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0005_alter_demanddata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demanddata',
            options={'ordering': ['-captured_at']},
        ),
        migrations.AddField(
            model_name='demanddata',
            name='captured_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of when the data was captured'),
        ),
    ]
